name: apphocvi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.3.1
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  json_annotation: ^4.11.0
  lucide_icons: ^0.257.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/Level_1/Topic_1_Pronouns/0003_mình/
    - assets/data/Level_1/Topic_1_Pronouns/0007_nó/
    - assets/data/Level_1/Topic_1_Pronouns/0014_người/
    - assets/data/Level_1/Topic_1_Pronouns/0029_anh/
    - assets/data/Level_1/Topic_1_Pronouns/0031_bạn/
    - assets/data/Level_1/Topic_1_Pronouns/0034_tôi/
    - assets/data/Level_1/Topic_1_Pronouns/0037_họ/
    - assets/data/Level_1/Topic_1_Pronouns/0044_chị/
    - assets/data/Level_1/Topic_2_States_Ownership/0001_là/
    - assets/data/Level_1/Topic_2_States_Ownership/0002_cái/
    - assets/data/Level_1/Topic_2_States_Ownership/0005_có/
    - assets/data/Level_1/Topic_2_States_Ownership/0008_không/
    - assets/data/Level_1/Topic_2_States_Ownership/0009_một/
    - assets/data/Level_1/Topic_2_States_Ownership/0010_và/
    - assets/data/Level_1/Topic_2_States_Ownership/0011_của/
    - assets/data/Level_1/Topic_2_States_Ownership/0013_đó/
    - assets/data/Level_1/Topic_2_States_Ownership/0025_này/
    - assets/data/Level_1/Topic_2_States_Ownership/0026_ở/
    - assets/data/Level_1/Topic_2_States_Ownership/0027_nhiều/
    - assets/data/Level_1/Topic_3_Basic_Actions/0024_làm/
    - assets/data/Level_1/Topic_3_Basic_Actions/0033_đi/
    - assets/data/Level_1/Topic_3_Basic_Actions/0041_nói/
    - assets/data/Level_1/Topic_3_Basic_Actions/0043_đến/
    - assets/data/Level_1/Topic_3_Basic_Actions/0048_biết/
    - assets/data/Level_1/Topic_3_Basic_Actions/0049_thấy/
    - assets/data/Level_1/Topic_3_Basic_Actions/0050_cám_ơn/
    - assets/data/Level_2/Topic_4_Time_Connectors/0004_thì/
    - assets/data/Level_2/Topic_4_Time_Connectors/0006_mà/
    - assets/data/Level_2/Topic_4_Time_Connectors/0012_những/
    - assets/data/Level_2/Topic_4_Time_Connectors/0015_cũng/
    - assets/data/Level_2/Topic_4_Time_Connectors/0016_được/
    - assets/data/Level_2/Topic_4_Time_Connectors/0017_sẽ/
    - assets/data/Level_2/Topic_4_Time_Connectors/0018_rất/
    - assets/data/Level_2/Topic_4_Time_Connectors/0019_phải/
    - assets/data/Level_2/Topic_4_Time_Connectors/0020_như/
    - assets/data/Level_2/Topic_4_Time_Connectors/0021_với/
    - assets/data/Level_2/Topic_4_Time_Connectors/0022_trong/
    - assets/data/Level_2/Topic_4_Time_Connectors/0023_để/
    - assets/data/Level_2/Topic_4_Time_Connectors/0028_về/
    - assets/data/Level_2/Topic_4_Time_Connectors/0030_gì/
    - assets/data/Level_2/Topic_4_Time_Connectors/0032_các/
    - assets/data/Level_2/Topic_4_Time_Connectors/0035_nhưng/
    - assets/data/Level_2/Topic_4_Time_Connectors/0036_đã/
    - assets/data/Level_2/Topic_4_Time_Connectors/0038_rồi/
    - assets/data/Level_2/Topic_4_Time_Connectors/0039_khi/
    - assets/data/Level_2/Topic_4_Time_Connectors/0040_đấy/
    - assets/data/Level_2/Topic_4_Time_Connectors/0042_có_thể/
    - assets/data/Level_2/Topic_4_Time_Connectors/0045_lại/
    - assets/data/Level_2/Topic_4_Time_Connectors/0046_nghĩ/
    - assets/data/Level_2/Topic_4_Time_Connectors/0047_hơn/
